/* ZLangCompilerOption.h */

/* File autogenerated by gengetopt version 2.3  */

#ifndef _ZLangCompilerOption_h
#define _ZLangCompilerOption_h

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Don't define PACKAGE and VERSION if we use automake.  */
#if defined PACKAGE
#  undef PACKAGE
#endif
#define PACKAGE "zlangc"
#if defined VERSION
#  undef VERSION
#endif
#define VERSION "1.0"

struct gengetopt_args_info {
  char * define_macro_arg;	/* A macro.  */
  char * include_path_arg;	/* A include path.  */
  char * object_file_arg;	/* Specific obejct file.  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int define_macro_given ;	/* Whether define-macro was given.  */
  int include_path_given ;	/* Whether include-path was given.  */
  int object_file_given ;	/* Whether object-file was given.  */
  int trace_lexer_given ;	/* Whether trace-lexer was given.  */
  int trace_ast_given ;	/* Whether trace-ast was given.  */
  int trace_symbol_table_given ;	/* Whether trace-symbol-table was given.  */
  int trace_code_given ;	/* Whether trace-code was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _ZLangCompilerOption_h */
