/*
  File autogenerated by gengetopt version 2.3  
  generated with the following command:
  gengetopt --unamed-opts --file-name=ZLangCompilerOption 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
/* Check for configure's getopt check result.  */
#ifndef HAVE_GETOPT_LONG
#include "getopt.h"
#else
#include <getopt.h>
#endif

#include "ZLangCompilerOption.h"


void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", PACKAGE, VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n"
"Usage: %s [OPTIONS]... [FILES]...\n\
   -h         --help                 Print help and exit\n\
   -V         --version              Print version and exit\n\
   -DSTRING   --define-macro=STRING  A macro\n\
   -ISTRING   --include-path=STRING  A include path\n\
   -oSTRING   --object-file=STRING   Specific obejct file\n\
              --trace-lexer          Trace lexer\n\
              --trace-ast            Trace AST generated\n\
              --trace-symbol-table   Trace symbol table generated\n\
              --trace-code           Trace byte code generated\n\
", PACKAGE);
}


static char *
gengetopt_strdup (char * s)
{
  char * n, * pn, * ps = s;
  while (*ps) ps++;
  n = (char *) malloc (1 + ps - s);
  if (n != NULL)
    {
      for (ps=s,pn=n; *ps; ps++,pn++)
        *pn = *ps;
      *pn = 0;
    }
  return n;
}


int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  int c;	/* Character of the parsed option.  */
  int missing_required_options = 0;	

  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->define_macro_given = 0 ;
  args_info->include_path_given = 0 ;
  args_info->object_file_given = 0 ;
  args_info->trace_lexer_given = 0 ;
  args_info->trace_ast_given = 0 ;
  args_info->trace_symbol_table_given = 0 ;
  args_info->trace_code_given = 0 ;
#define clear_args() { \
  args_info->define_macro_arg = NULL; \
  args_info->include_path_arg = NULL; \
  args_info->object_file_arg = NULL; \
}

  clear_args();

  args_info->inputs = NULL;
  args_info->inputs_num = 0;

  while (1)
    {
      int option_index = 0;
      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "define-macro",	1, NULL, 'D' },
        { "include-path",	1, NULL, 'I' },
        { "object-file",	1, NULL, 'o' },
        { "trace-lexer",	0, NULL, 0 },
        { "trace-ast",	0, NULL, 0 },
        { "trace-symbol-table",	0, NULL, 0 },
        { "trace-code",	0, NULL, 0 },
        { NULL,	0, NULL, 0 }
      };

      c = getopt_long (argc, argv, "hVD:I:o:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          clear_args ();
          cmdline_parser_print_help ();
          exit (0);

        case 'V':	/* Print version and exit.  */
          clear_args ();
          cmdline_parser_print_version ();
          exit (0);

        case 'D':	/* A macro.  */
          if (args_info->define_macro_given)
            {
              fprintf (stderr, "%s: `--define-macro' (`-D') option given more than once\n", PACKAGE);
              clear_args ();
              cmdline_parser_print_help ();
              exit (1);
            }
          args_info->define_macro_given = 1;
          args_info->define_macro_arg = gengetopt_strdup (optarg);
          break;

        case 'I':	/* A include path.  */
          if (args_info->include_path_given)
            {
              fprintf (stderr, "%s: `--include-path' (`-I') option given more than once\n", PACKAGE);
              clear_args ();
              cmdline_parser_print_help ();
              exit (1);
            }
          args_info->include_path_given = 1;
          args_info->include_path_arg = gengetopt_strdup (optarg);
          break;

        case 'o':	/* Specific obejct file.  */
          if (args_info->object_file_given)
            {
              fprintf (stderr, "%s: `--object-file' (`-o') option given more than once\n", PACKAGE);
              clear_args ();
              cmdline_parser_print_help ();
              exit (1);
            }
          args_info->object_file_given = 1;
          args_info->object_file_arg = gengetopt_strdup (optarg);
          break;

        
        
        
        
        case 0:	/* Long option with no short option */
          /* Trace lexer.  */
          if (strcmp (long_options[option_index].name, "trace-lexer") == 0)
          {
            if (args_info->trace_lexer_given)
              {
                fprintf (stderr, "%s: `--trace-lexer' option given more than once\n", PACKAGE);
                clear_args ();
                cmdline_parser_print_help ();
                exit (1);
              }
            args_info->trace_lexer_given = 1;
            break;
          }
          /* Trace AST generated.  */
          else if (strcmp (long_options[option_index].name, "trace-ast") == 0)
          {
            if (args_info->trace_ast_given)
              {
                fprintf (stderr, "%s: `--trace-ast' option given more than once\n", PACKAGE);
                clear_args ();
                cmdline_parser_print_help ();
                exit (1);
              }
            args_info->trace_ast_given = 1;
            break;
          }
          /* Trace symbol table generated.  */
          else if (strcmp (long_options[option_index].name, "trace-symbol-table") == 0)
          {
            if (args_info->trace_symbol_table_given)
              {
                fprintf (stderr, "%s: `--trace-symbol-table' option given more than once\n", PACKAGE);
                clear_args ();
                cmdline_parser_print_help ();
                exit (1);
              }
            args_info->trace_symbol_table_given = 1;
            break;
          }
          /* Trace byte code generated.  */
          else if (strcmp (long_options[option_index].name, "trace-code") == 0)
          {
            if (args_info->trace_code_given)
              {
                fprintf (stderr, "%s: `--trace-code' option given more than once\n", PACKAGE);
                clear_args ();
                cmdline_parser_print_help ();
                exit (1);
              }
            args_info->trace_code_given = 1;
            break;
          }

        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          exit (1);

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c\n", PACKAGE, c);
          abort ();
        } /* switch */
    } /* while */

  if ( missing_required_options )
    exit (1);

  if (optind < argc)
    {
      int i = 0 ;

      args_info->inputs_num = argc - optind ;
      args_info->inputs = 
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind++]) ; 
    }

  return 0;
}
